server:
    port: 9090

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
    sql:
        init:
            mode: always
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}





    #config:
    #    activate:
    #        on-profile: ci,test
    #datasource:
    #    driverClassName: org.h2.Driver
    #    url: jdbc:h2:mem:shareit
    #    username: test
    #    password: test


