logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG

server:
  port: 8080

shareit-server:
  url: ${SHAREIT_SERVER_URL}